package common;

public enum PayloadType 
{
    CONNECT, DISCONNECT, MESSAGE, CLIENT_ID, RESET_USER_LIST,
    SYNC_CLIENT, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
    READY, PHASE, COLOR_UPDATE, COORDINATES_AND_COLOR, BOARD_COMMAND, BOARD_UPDATE, START_GUESS, COMMAND, GUESS, NEW_ROUND, CORRECT_GUESS, INCORRECT_GUESS
}